// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import {
  Modal,
  ConfigProvider,
  message,
  notification,
} from 'antd';
import { ApplyPluginsType } from 'umi';
import { getPluginManager } from '../core/plugin';

let cacheAntdConfig = null;

const getAntdConfig = () => {
  if(!cacheAntdConfig){
    cacheAntdConfig = getPluginManager().applyPlugins({
      key: 'antd',
      type: ApplyPluginsType.modify,
      initialValue: {
        ...{"theme":{"@primary-color":"#4461EB","@success-color":"#5cb85c","@warning-color":"#ffbf00","@error-color":"#f85a5a","@a-hover-color":"#6f8bf7","@font-size-base":"12px","@border-radius-base":"4px","@tabs-title-font-size":"14px","@tabs-horizontal-margin":"0 16px 0 0","@tabs-horizontal-padding":"12px 16px","@input-padding-vertical-base":"5.8px","@ant-prefix":"ant","primaryColor":"#4461EB","token":{"colorPrimary":"#4461EB","colorInfoText":"#4461EB","colorInfo":"#4461EB","colorPrimaryText":"#4461EB","colorLink":"#4461EB","borderRadius":2,"colorTextHeading":"rgba(0, 0, 0, 0.65)"}}},
      },
    });
  }
  return cacheAntdConfig;
}

export function rootContainer(rawContainer) {
  const {
    appConfig,
    ...finalConfigProvider
  } = getAntdConfig();
  let container = rawContainer;
  if (finalConfigProvider.prefixCls) {
    Modal.config({
      rootPrefixCls: finalConfigProvider.prefixCls
    });
    message.config({
      prefixCls: `${finalConfigProvider.prefixCls}-message`
    });
    notification.config({
      prefixCls: `${finalConfigProvider.prefixCls}-notification`
    });
  }

  if (finalConfigProvider.iconPrefixCls) {
    // Icons in message need to set iconPrefixCls via ConfigProvider.config()
    ConfigProvider.config({
      iconPrefixCls: finalConfigProvider.iconPrefixCls,
    });
  };
  container = <ConfigProvider {...finalConfigProvider}>{container}</ConfigProvider>;

  return container;
}
