// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'C:/Users/ren.siwei3/Desktop/code/voice/src/models/app';

export const models = {
model_1: { namespace: 'app', model: model_1 },
} as const
