// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'C:/Users/ren.siwei3/Desktop/code/voice/node_modules/.pnpm/@umijs+renderer-react@4.0.66_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react';
export type {  History } from 'C:/Users/ren.siwei3/Desktop/code/voice/node_modules/.pnpm/@umijs+renderer-react@4.0.66_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'C:/Users/ren.siwei3/Desktop/code/voice/node_modules/.pnpm/umi@4.0.66_ew4xvmffxjmn2z3ltyxgp7nyhe/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'C:/Users/ren.siwei3/Desktop/code/voice/src/.umi/plugin-access';
export { connect, useDispatch, useStore, useSelector, getDvaApp } from 'C:/Users/ren.siwei3/Desktop/code/voice/src/.umi/plugin-dva';
export { Provider, useModel } from 'C:/Users/ren.siwei3/Desktop/code/voice/src/.umi/plugin-model';
// plugins types.d.ts
export * from 'C:/Users/ren.siwei3/Desktop/code/voice/src/.umi/plugin-access/types.d';
export * from 'C:/Users/ren.siwei3/Desktop/code/voice/src/.umi/plugin-antd/types.d';
export * from 'C:/Users/ren.siwei3/Desktop/code/voice/src/.umi/plugin-dva/types.d';
